### ISSUE TITLE
«The locale '' is no known locale»

### ISSUE THREAD

**Issue by dmitrii-fediuk** [trackspecmotorsports/site#13]
```
a:5:{i:0;s:32:"The locale '' is no known locale";i:1;s:5253:"#0 app/code/core/Zend/Date.php(1091): Zend_Date->_calculate('set', '2022-08-24 00:0...', NULL, '')
#1 app/code/core/Zend/Date.php(210): Zend_Date->set('2022-08-24 00:0...', NULL, '')
#2 app/code/local/Meigee/ThemeOptionsIndigo/Helper/Data.php(42): Zend_Date->__construct('2022-08-24 00:0...')
#3 app/design/frontend/indigo/default/template/ajax/catalog/product/view/list.phtml(202): Meigee_ThemeOptionsIndigo_Helper_Data->getProductLabels(Object(Mage_Catalog_Model_Product), 'new')
#4 app/code/core/Mage/Core/Block/Template.php(241): include('/chroot/home/tr...')
#5 app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/indigo...')
#6 app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#7 app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Template->_toHtml()
#8 app/code/core/Mage/Core/Block/Abstract.php(637): Mage_Core_Block_Abstract->toHtml()
#9 app/code/core/Mage/Core/Block/Abstract.php(581): Mage_Core_Block_Abstract->_getChildHtml('product_list', true)
#10 app/code/core/Mage/Catalog/Block/Category/View.php(90): Mage_Core_Block_Abstract->getChildHtml('product_list')
#11 app/design/frontend/base/default/template/catalog/category/view.phtml(70): Mage_Catalog_Block_Category_View->getProductListHtml()
#12 app/code/core/Mage/Core/Block/Template.php(241): include('/chroot/home/tr...')
#13 app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/base/d...')
#14 app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#15 app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Template->_toHtml()
#16 app/code/core/Mage/Core/Block/Text/List.php(43): Mage_Core_Block_Abstract->toHtml()
#17 app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Text_List->_toHtml()
#18 app/code/core/Mage/Core/Block/Abstract.php(637): Mage_Core_Block_Abstract->toHtml()
#19 app/code/core/Mage/Core/Block/Abstract.php(581): Mage_Core_Block_Abstract->_getChildHtml('content', true)
#20 app/design/frontend/indigo/default/template/page/2columns-left.phtml(35): Mage_Core_Block_Abstract->getChildHtml('content')
#21 app/code/core/Mage/Core/Block/Template.php(241): include('/chroot/home/tr...')
#22 app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/indigo...')
#23 app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#24 app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Template->_toHtml()
#25 app/code/core/Mage/Core/Model/Layout.php(555): Mage_Core_Block_Abstract->toHtml()
#26 app/code/core/Mage/Core/Controller/Varien/Action.php(390): Mage_Core_Model_Layout->getOutput()
#27 app/code/community/Magehouse/Slider/controllers/Catalog/CategoryController.php(112): Mage_Core_Controller_Varien_Action->renderLayout()
#28 app/code/core/Mage/Core/Controller/Varien/Action.php(418): Magehouse_Slider_Catalog_CategoryController->viewAction()
#29 app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('view')
#30 app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#31 app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#32 app/Mage.php(689): Mage_Core_Model_App->run(Array)
#33 index.php(95): Mage::run('', 'store')
#34 {main}";s:3:"url";s:11:"/roll-cages";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:7:"default";}
```

**Comment by dmitrii-fediuk** [comment]
[Zend Framework 1 bug: «The locale '' is no known locale»](https://mage2.pro/t/4255)
