### ISSUE TITLE
`/admin/dashboard/tunnel`: «Unable to read response, or response is empty»

### ISSUE THREAD

**Issue by dmitrii-fediuk** [trackspecmotorsports/site#14]
```
a:5:{i:0;s:45:"Unable to read response, or response is empty";i:1;s:1183:"#0 lib/Varien/Http/Client.php(61): Zend_Http_Client->request('GET')
#1 app/code/core/Mage/Adminhtml/controllers/DashboardController.php(99): Varien_Http_Client->request('GET')
#2 app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Adminhtml_DashboardController->tunnelAction()
#3 app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('tunnel')
#4 app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#5 app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#6 app/Mage.php(689): Mage_Core_Model_App->run(Array)
#7 index.php(95): Mage::run('', 'store')
#8 {main}";s:3:"url";s:703:"/index.php/trackspe_admin/dashboard/tunnel/key/a8cc347a27928e1ed9c12496e871ed6b/?ga=YTo5OntzOjM6ImNodCI7czoyOiJsYyI7czozOiJjaGYiO3M6Mzk6ImJnLHMsZjRmNGY0fGMsbGcsOTAsZmZmZmZmLDAuMSxlZGVkZWQsMCI7czozOiJjaG0iO3M6MTQ6IkIsZjRkNGIyLDAsMCwwIjtzOjQ6ImNoY28iO3M6NjoiZGI0ODE0IjtzOjM6ImNoZCI7czo0ODoiZTpPT1ZWSEhPT09PampWVk9PQUFjY09PY2NWVk9PVlZxcU9PY2NqajQ0VlZxcUhIIjtzOjQ6ImNoeHQiO3M6MzoieCx5IjtzOjQ6ImNoeGwiO3M6MTA4OiIwOnx8fDMvMy8yMDIyfHx8My82LzIwMjJ8fHwzLzkvMjAyMnx8fDMvMTIvMjAyMnx8fDMvMTUvMjAyMnx8fDMvMTgvMjAyMnx8fDMvMjEvMjAyMnx8fDE6fDB8MXwyfDN8NHw1fDZ8N3w4fDkiO3M6MzoiY2hzIjtzOjc6IjU4N3gzMDAiO3M6MzoiY2hnIjtzOjM1OiI0LjU0NTQ1NDU0NTQ1NDUsMTEuMTExMTExMTExMTExLDEsMCI7fQ%253D%253D&h=0cf4dbb79b9f1d466acd8c2867258e70";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:5:"admin";}
```

**Comment by dmitrii-fediuk** [comment]
[magento.stackexchange.com/questions/125315](https://magento.stackexchange.com/questions/125315)
The Magento backend was broken: https://github.com/trackspecmotorsports/site/issues/1
It caused the issue.
