### ISSUE TITLE
[PayPal #15004] «Gateway Decline» / «Please enter a valid Credit Card Verification Number»

### ISSUE THREAD

**Issue by dmitrii-fediuk** [trackspecmotorsports/site#20]
```
2023-06-23T18:19:29+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'PayPal NVP gateway errors: This transaction cannot be processed. Please enter a valid Credit Card Verification Number (#15004: Gateway Decline). Correlation ID: 6f35ac766b5ca. Version: 72.0.' in app/Mage.php:585
Stack trace:
#0 app/code/core/Mage/Paypal/Model/Api/Nvp.php(1050): Mage::exception('Mage_Core', 'PayPal NVP gate...')
#1 app/code/core/Mage/Paypal/Model/Api/Nvp.php(1011): Mage_Paypal_Model_Api_Nvp->_handleCallErrors(Array)
#2 app/code/core/Mage/Paypal/Model/Api/Nvp.php(662): Mage_Paypal_Model_Api_Nvp->call('DoDirectPayment', Array)
#3 app/code/core/Mage/Paypal/Model/Direct.php(343): Mage_Paypal_Model_Api_Nvp->callDoDirectPayment()
#4 app/code/core/Mage/Paypal/Model/Direct.php(202): Mage_Paypal_Model_Direct->_placeOrder(Object(Mage_Sales_Model_Order_Payment), '175.38')
#5 app/code/core/Mage/Sales/Model/Order/Payment.php(443): Mage_Paypal_Model_Direct->capture(Object(Mage_Sales_Model_Order_Payment), '175.38')
#6 app/code/core/Mage/Sales/Model/Order/Invoice.php(385): Mage_Sales_Model_Order_Payment->capture(Object(Mage_Sales_Model_Order_Invoice))
#7 app/code/core/Mage/Sales/Model/Order/Payment.php(607): Mage_Sales_Model_Order_Invoice->capture()
#8 app/code/core/Mage/Sales/Model/Order/Payment.php(410): Mage_Sales_Model_Order_Payment->_invoice()
#9 app/code/core/Mage/Sales/Model/Order/Payment.php(348): Mage_Sales_Model_Order_Payment->capture(NULL)
#10 app/code/core/Mage/Sales/Model/Order.php(886): Mage_Sales_Model_Order_Payment->place()
#11 app/code/core/Mage/Sales/Model/Order.php(1104): Mage_Sales_Model_Order->_placePayment()
#12 [internal function]: Mage_Sales_Model_Order->place()
#13 app/code/core/Mage/Core/Model/Resource/Transaction.php(105): call_user_func(Array)
#14 app/code/core/Mage/Core/Model/Resource/Transaction.php(159): Mage_Core_Model_Resource_Transaction->_runCallbacks()
#15 app/code/core/Mage/Sales/Model/Service/Quote.php(189): Mage_Core_Model_Resource_Transaction->save()
#16 app/code/core/Mage/Sales/Model/Service/Quote.php(249): Mage_Sales_Model_Service_Quote->submitOrder()
#17 app/code/local/IWD/OnepageCheckout/Model/Type/Geo.php(762): Mage_Sales_Model_Service_Quote->submitAll()
#18 app/code/local/IWD/OnepageCheckout/controllers/IndexController.php(781): IWD_OnepageCheckout_Model_Type_Geo->saveOrder()
#19 app/code/core/Mage/Core/Controller/Varien/Action.php(418): IWD_OnepageCheckout_IndexController->saveOrderAction()
#20 app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('saveOrder')
#21 app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#22 app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#23 app/Mage.php(689): Mage_Core_Model_App->run(Array)
#24 index.php(95): Mage::run('', 'store')
#25 {main}
```

**Comment by dmitrii-fediuk** [comment]
```
2023-06-23T18:20:32+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'PayPal gateway has rejected request. This transaction cannot be processed (#15005: Processor Decline).' in app/Mage.php:585
Stack trace:
#0 app/code/core/Mage/Paypal/Model/Api/Nvp.php(1050): Mage::exception('Mage_Core', 'PayPal NVP gate...')
#1 app/code/core/Mage/Paypal/Model/Api/Nvp.php(1011): Mage_Paypal_Model_Api_Nvp->_handleCallErrors(Array)
#2 app/code/core/Mage/Paypal/Model/Api/Nvp.php(662): Mage_Paypal_Model_Api_Nvp->call('DoDirectPayment', Array)
#3 app/code/core/Mage/Paypal/Model/Direct.php(343): Mage_Paypal_Model_Api_Nvp->callDoDirectPayment()
#4 app/code/core/Mage/Paypal/Model/Direct.php(202): Mage_Paypal_Model_Direct->_placeOrder(Object(Mage_Sales_Model_Order_Payment), '175.38')
#5 app/code/core/Mage/Sales/Model/Order/Payment.php(443): Mage_Paypal_Model_Direct->capture(Object(Mage_Sales_Model_Order_Payment), '175.38')
#6 app/code/core/Mage/Sales/Model/Order/Invoice.php(385): Mage_Sales_Model_Order_Payment->capture(Object(Mage_Sales_Model_Order_Invoice))
#7 app/code/core/Mage/Sales/Model/Order/Payment.php(607): Mage_Sales_Model_Order_Invoice->capture()
#8 app/code/core/Mage/Sales/Model/Order/Payment.php(410): Mage_Sales_Model_Order_Payment->_invoice()
#9 app/code/core/Mage/Sales/Model/Order/Payment.php(348): Mage_Sales_Model_Order_Payment->capture(NULL)
#10 app/code/core/Mage/Sales/Model/Order.php(886): Mage_Sales_Model_Order_Payment->place()
#11 app/code/core/Mage/Sales/Model/Order.php(1104): Mage_Sales_Model_Order->_placePayment()
#12 [internal function]: Mage_Sales_Model_Order->place()
#13 app/code/core/Mage/Core/Model/Resource/Transaction.php(105): call_user_func(Array)
#14 app/code/core/Mage/Core/Model/Resource/Transaction.php(159): Mage_Core_Model_Resource_Transaction->_runCallbacks()
#15 app/code/core/Mage/Sales/Model/Service/Quote.php(189): Mage_Core_Model_Resource_Transaction->save()
#16 app/code/core/Mage/Sales/Model/Service/Quote.php(249): Mage_Sales_Model_Service_Quote->submitOrder()
#17 app/code/local/IWD/OnepageCheckout/Model/Type/Geo.php(762): Mage_Sales_Model_Service_Quote->submitAll()
#18 app/code/local/IWD/OnepageCheckout/controllers/IndexController.php(781): IWD_OnepageCheckout_Model_Type_Geo->saveOrder()
#19 app/code/core/Mage/Core/Controller/Varien/Action.php(418): IWD_OnepageCheckout_IndexController->saveOrderAction()
#20 app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('saveOrder')
#21 app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#22 app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#23 app/Mage.php(689): Mage_Core_Model_App->run(Array)
#24 index.php(95): Mage::run('', 'store')
#25 {main}
```
